# 时间信息
start_ddate: '2016010112'  # yyyymndd
end_ddate  : '2016010512'  # yyyymndd

# 起报时间间隔
fcst_step: 24 # hours

# GRAPES试验名称和数据路径 
# ctlfile_dir: './87_fcst_ctl/'
# exprs:
#   'CTRL' : './87_fcst_ctl/'
#   'ASSI' : './87_fcst_ctl/'
exprs:
  'CTRL' : './87_fcst_ctl/'

# GRAPES数据转换路径
exdata_root_dir: './ex_data/'

# 转化的线程数
nthreads: 1

# 统计绘图变量和层次:
# 可供选择的变量和层次: ['u','v','t','h','w','q','24hrain','t2m', 'shf', 'phf']
#                     [1000.,925.,850.,700.,600.,500.,400.,300.,200.,100.,50.,10.]
# st_vars: ['u','v','t','h','w','q','24hrain','t2m', 'shf', 'phf']
st_vars:  ['u', 'v', 'h']
# plot_levels: [1000.,925.,850.,700.,600.,500.,400.,300.,200.,100.]
plot_levels: [500.]

# 绘制纬圈平均
plot_zonalmean: True

# 纬圈平均色标
clevel_zonalmean_PMF:
  u: [-8, -6, -4, -2, -1, -0.5, 0.5, 1, 2, 4, 6, 8]
  v: [-1.00, -0.75, -0.50, -0.25, -0.10, -0.05, 0.05, 0.10, 0.25, 0.50, 0.75, 1.00]
  t: [-4, -3, -2, -1, -0.5, 0.5, 1, 2, 3, 4]
  h: [-120, -80, -40, -20, -10, -5, 5, 10, 20, 40, 80, 120]
  q: [-1.00, -0.75, -0.50, -0.25, -0.10, -0.05, 0.05, 0.10, 0.25, 0.50, 0.75, 1.00]

# 预报时长
fcst: [0, 24] # hours

# 画图设置
# 图片路径和类型
pic_root_dir: './pic'
pic_prefix: 'png'

# 画图前是否清理原出图文件夹
clean_plot: True

# 画图区域
# 可供选择的区域 ['Global', 'E_Asia', 'North_P', 'South_P', 'Tropics']
# plot_areas:
#   "u v t h w q": ['Global', 'E_Asia', 'North_P', 'South_P']
#   "24hrain shf phf" : ['Global', 'E_Asia']
#   "t2m" : ['Global']

plot_areas:
  "u v t h w q": ['Global']
  "shf phf" : ['Global']
  "24hrain" : ['Global']
  "t2m" : ['Global']

plot_types: ['G', 'F', 'GMF']

plot_types_name:
  G:    'GRAPES'
  F:    'FNL'
  GMF:  'GRAPES - FNL'

# 个例画图
plot_cases: False
# 观测文件路径
obs_dir: './nmc_obs/'
# 个例起报时间
case_ini_times: ['2016010112']
# 个例预报时间
case_fcst_hours: [12,36,60]
# 是否使用新配色方案
newcolorscheme: False
