# 时间信息
start_ddate: '2016010112'  # yyyymndd
end_ddate  : '2016010512'  # yyyymndd

# 数据路径 
ctlfile_dir: './87_fcst_ctl/'

# 数据转换路径
exdata_dir: './ex_data/'

# 统计变量和统计等压层
st_vars  : ['u','v','t','h']
# st_levels: [1000.,925.,850.,700.,600.,500.,400.,300.,200.,100.,50.,10.]
st_levels: [500.]

# 预报时长
fcst: [0,72,120] #hours
# fcst: [0] #hours

# 图片类型
pic_prefix: 'png'
make_gif: True

# 画图设置
# plot_areas: ['Global', 'E_Asia', 'North_P', 'South_P']
plot_areas: ['North_P']

clevel_step:
  u: 2
  v: 2
  t: 3
  h: 30

variable_name:
  t:  'Temperature [K]'
  u:  'U Wind [m/s]'
  v:  'V wind [m/s]'
  h:  'Geopotential Height [gpm]'
