# 时间信息
start_ddate: '2016010112'  # yyyymndd
end_ddate  : '2016010512'  # yyyymndd

# 起报时间间隔
fcst_step: 24 # hours

# GRAPES数据路径 
ctlfile_dir: './87_fcst_ctl/'

# GRAPES数据转换路径
exdata_dir: './ex_data/'

# FNL数据路径
fnl_dir: './fnl_data/'

# FNL数据变量名
fnl_varname:
  u: 'UGRD_P0_L100_GLL0'
  v: 'VGRD_P0_L100_GLL0'
  t: 'TMP_P0_L100_GLL0'
  h: 'HGT_P0_L100_GLL0'

# 提取变量和统计变量
ex_vars  : ['u','v','t','h','w','q2','rainc','rainnc']
# st_vars  : ['u','v','t','h','w_cm2s','q2',24hrain']
st_vars  : ['w_cm2s', 'q2', 't', 'h']

# avoid ploting initial
moist_vars : ['q2']

# avoid ploting FNL
noFNL_vars: ['24hrain', 'w_cm2s', 'q2']

# align with 00z vars
align_vars: ['24hrain']


# 提取等压层和统计等压层
ex_levels: [1000.,925.,850.,700.,600.,500.,400.,300.,200.,100.,50.,10.]
st_levels: [500.]

# 预报时长
fcst: [0,72] # hours
# 预报时间步长: 不作用于出图脚本，只是为了方便生成动图和拼接图片的脚本
time_incr: 12

# 图片类型
pic_prefix: 'png'

# 画图设置
clean_plot: True

# plot_areas: ['Global', 'E_Asia', 'North_P', 'South_P']
plot_areas: ['North_P']

plot_types: ['P', 'F', 'PMF']
# plot_types: ['P']

plot_types_name:
  P:    'Prediction'
  F:    'FNL'
  PMF:  'Prediction - FNL'

clevel_step:
  u: 2
  v: 2
  t: 3
  h: 30
  w_cm2s: 0.04
  q2: 0.2

clevel_step_PMF:
  u: 1
  v: 1
  t: 1
  h: 10
  w_cm2s: 0.01
  q2: 0.05

clevel_custom:
  24hrain: [1, 2, 4, 6, 8, 10, 12, 16, 20, 32, 64]

variable_name:
  t:  'Temperature [K]'
  u:  'U Wind [m/s]'
  v:  'V wind [m/s]'
  h:  'Geopotential Height [gpm]'
  w_cm2s:  'Vertical Velocity [cm/s]'
  q2: 'Specific Humidity [g/kg]'
  24hrain: '24hours precipitation [mm]'

# 个例画图
plot_cases: True
# 观测文件路径
obs_dir: './nmc_obs/'
# 个例起报时间
case_ini_times: ['2016010112']
# 个例预报时间
case_fcst_hours: [12,36,60]
# 是否使用新配色方案
newcolorscheme: True
