# 时间信息
start_ddate: '2016010112'  # yyyymndd
end_ddate  : '2016010112'  # yyyymndd

# 起报时间间隔
fcst_step: 24 # hours

# GRAPES试验名称和数据路径 
# ctlfile_dir: './87_fcst_ctl/'
# exprs:
#   'CTRL' : './87_fcst_ctl/'
#   'ASSI' : './87_fcst_ctl/'
exprs:
  'CTRL' : './87_fcst_ctl/'

# GRAPES数据转换路径
exdata_root_dir: './ex_data/'

# 统计绘图变量和层次:
# 可供选择的变量和层次: ['u','v','t','h','w','q','24hrain','t2m', 'shf', 'phf']
#                     [1000.,925.,850.,700.,600.,500.,400.,300.,200.,100.,50.,10.]
# st_vars: ['u','v','t','h','w','q','24hrain','t2m', 'shf', 'phf']
st_vars:  ['h', '24hrain']
# st_levels: [1000.,925.,850.,700.,600.,500.,400.,300.,200.,100.]
st_levels: [500.]

# 预报时长
fcst: [0, 24] # hours

# 画图设置
# 图片路径和类型
pic_root_dir: './pic'
pic_prefix: 'png'

# 画图前是否清理原出图文件夹
clean_plot: True

# 画图区域
# 可供选择的区域 ['Global', 'E_Asia', 'North_P', 'South_P', 'Tropics']
# plot_areas:
#   "u v t h w q": ['Global', 'E_Asia', 'North_P', 'South_P']
#   "24hrain shf phf" : ['Global', 'E_Asia']
#   "t2m" : ['Global']

# plot_areas:
#   "u v t h w q": ['Global', 'E_Asia']
#   "shf phf" : ['Global']
#   "24hrain" : ['Global', 'E_Asia']
#   "t2m" : ['Global']

plot_areas:
  "u v t h w q": ['Global']
  "shf phf" : ['Global']
  "24hrain" : ['Global', 'E_Asia']
  "t2m" : ['Global']

plot_types: ['G', 'F', 'GMF']

plot_types_name:
  G:    'GRAPES'
  F:    'FNL'
  GMF:  'GRAPES - FNL'

# 个例画图
plot_cases: False
# 观测文件路径
obs_dir: './nmc_obs/'
# 个例起报时间
case_ini_times: ['2016010112']
# 个例预报时间
case_fcst_hours: [12,36,60]
# 是否使用新配色方案
newcolorscheme: False
