# configure file for developers

# 平台
platform: 'PC'    # 'Pi'
# platform: 'Pi'

# FNL数据路径
fnl_dir: './fnl_data/'
# fnl_dir: '/g1/COMMONDATA/obs/EXPR/NWPC/glob/fnl/'
temp_fnl_dir: './temp/fnl_data_tmp/'


# FNL加速硬盘缓冲区
dump_dir: './temp/fnl_pkl/'
remove_dump: True

# 运行模式 plot / debug
run_mode: 'plot'

# 格点雨量观测值路径 
use_gridrain_type: 'type2'
gridrain:
  type1:
    gridrain_dir: './obs_gridrain_test/'
    gridrain_sample: './obs_gridrain/20160101/Z_SURF_C_BABJ_20190603001645_P_CMPA_NRT_CHN_0P05_HOR-PRE-2016010100.nc'
  type2:
    gridrain_dir: './cmp_pre_gridrain/'
    # gridrain_dir: '/g11/phy_xp/COMMDATA/rainfall/china/nmic/'
    gridrain_sample: './cmp_pre_gridrain/SURF_CLI_CHN_MERGE_CMP_PRE_HOUR_GRID_0.10-2016010100.grd'
    #  gridrain_sample: '/g11/phy_xp/COMMDATA/rainfall/china/nmic/SURF_CLI_CHN_MERGE_CMP_PRE_HOUR_GRID_0.10-2016010100.grd'

# 蒙版文件路径
mask_dir: './Cmodule/chinamask/country1'
# mask_dir: '/g3/wanghao/Python/Cmodule/GRAPES_VS_FNL/chinamask/country1'

# 插值变量
def_interp2fnl_vars: ['u', 'v', 't', 'h', 'q2']

# 提取变量和层次
ex_vars  : ['u','v','t','h','w','q2','rainc','rainnc', 'hfxa', 'qfxa', 't2m']
ex_levels: [1000.,925.,850.,700.,600.,500.,400.,300.,200.,100.,50.,10.]

# FNL数据变量名
fnl_varname:
  u: 'u' # [m/s]
  v: 'v' # [m/s]
  t: 't' # [K]
  h: 'gh' # [gpm]
  rh: 'r' # [%]
  p: 'isobaricInhPa' # [hPa]

# GRAPES数据变量名
grapes_varname:
  u: 'u'
  v: 'v'
  t: 't'
  h: 'h'
  w_m2s: 'w'
  q_kg2kg: 'q2'
  lat: 'latitude'
  lon: 'longitude'
  lev: 'levels'
  time: 'times'
  rainc: 'rainc'
  rainnc: 'rainnc'
  t2m: 't2m'
  hf: 'hfxa'
  qf: 'qfxa'

variable_name:
  t:  'Temperature [K]'
  u:  'U Wind [m/s]'
  v:  'V wind [m/s]'
  h:  'Geopotential Height [gpm]'
  w:  'Vertical Velocity [cm/s]'
  q: 'Specific Humidity [g/kg]'
  24hrain: '24hr Precipitation [mm]'
  t2m: '2m Temperature [K]'
  shf: '24hr Mean Surface Sensible Heat Flux [$W \cdot m^{-2} \cdot s^{-1}$]'
  phf: '24hr Mean Surface Latent Heat Flux [$W \cdot m^{-2} \cdot s^{-1}$]'

# 可画图变量
plotable_vars: ['u','v','t','h','w','q','24hrain','t2m', 'shf', 'phf']

# 是否启用多进程作图
multi_process: False

var_ndims:
  u: 4
  v: 4
  t: 4
  h: 4
  w: 4
  q: 4
  24hrain: 3
  t2m: 3
  shf: 3
  phf: 3

# 画图归一化参数
symlognorm_params:
  w:
    linthresh: 1
    linscale: 1.2
    vmin: -32
    vmax: 32
  shf:
    linthresh: 80
    linscale: 1.4
    vmin: -200
    vmax: 400

lognorm_params:
  24hrain:

# 填色色标间隔
clevel_step:
  u: 2
  v: 2
  t: 1
  h: 40
  q: 0.1
  t2m: 1
  shf: 10
  phf: 10

clevel_step_PMF:
  u: 1
  v: 1
  t: 0.5
  h: 10
  q: 0.1
  t2m: 0.5
  shf: 5
  phf: 5

clevel_step_zonalmean:
  u: 2
  v: 0.2
  t: 1
  h: 40
  q: 0.1

symlognorm_params_PMF:
  24hrain:
    linthresh: 0.1
    linscale: 1.5
    vmin: -25
    vmax: 25
  w:
    linthresh: 1.0
    linscale: 1.5
    vmin: -40
    vmax: 40
  shf:
    linthresh: 10.0
    linscale: 1.5
    vmin: -200
    vmax: 200
  phf:
    linthresh: 10.0
    linscale: 1.5
    vmin: -200
    vmax: 200

symlognorm_params_zonalmean_PMF:
  u:
    linthresh: 1
    linscale: 1.0
    vmin: -8
    vmax: 8
  v:
    linthresh: 0.10
    linscale: 0.6
    vmin: -1.0
    vmax: 1.0
  t:
    linthresh: 1
    linscale: 1.0
    vmin: -4
    vmax: 4
  h:
    linthresh: 10
    linscale: 1.0
    vmin: -120
    vmax: 120
  q:
    linthresh: 0.10
    linscale: 1.0
    vmin: -1.0
    vmax: 1.0

# 自定义clevels
clevel_custom:
  24hrain: [0.1, 1, 2, 4, 6, 8, 10, 12, 16, 20, 32, 64]
  w: [-32, -16, -8, -4, -2, -1, -0.5, -0.2, 0, 0.2, 0.5, 1, 2, 4, 6, 8, 16, 32]
  shf: [-200, -100, -50, -25, 0, 25, 50, 100, 200, 400]
  phf: [0, 50, 100, 150, 200, 250, 300, 350, 400, 450]

clevel_custom_PMF:
  24hrain: [-25,-13,-4,-0.1,-0.01,0.01,0.1,4,13,25]
  w: [-40, -20, -10, -5, -2, -1, -0.5, 0.5, 1, 2, 5, 10, 20, 40]
  phf: [-200, -100, -50, -25, -10, -5, -1, 1, 5, 10, 25, 50, 100, 200]
  shf: [-200, -100, -50, -25, -10, -5, -1, 1, 5, 10, 25, 50, 100, 200]
  t2m: [-5, -4, -3, -2, -1, -0.5, 0.5, 1, 2, 3, 4, 5]


# 一些特殊变量
# avoid ploting initial
moist_vars : ['q', 'w', 't2m']

# avoid ploting FNL
noFNL_vars: ['24hrain', 'w', 't2m', 'shf', 'phf']

# align with 00z vars
align_vars: ['24hrain']

# 24hmean var
daymean_vars: ['shf', 'phf']

# 24hacc var
dayacc_vars: ['24hrain']

# 图片质量
plot_dpi: 300
# 是否制作拼图
make_comp: True
# 是否制作动图 
make_gif: False

# 原始图片路径
origin: 'origin'
# 拼图路径
comp: 'comp'
# 纬圈平均路径
zonalmean: 'zonalmean'
# 动图路径
gif: 'gif'
# 案例图路径
case: 'case'

# zonal mean level ticks
levelticks: [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]
