# configure file for developers

# 平台
platform: 'PC'    # 'Pi'

# FNL数据路径
fnl_dir: './fnl_data/'

# FNL加速硬盘缓冲区
dump_dir: './temp/'
remove_dump: True

# 提取变量和层次
ex_vars  : ['u','v','t','h','w','q2','rainc','rainnc', 'hfxa', 'qfxa', 't2m']
ex_levels: [1000.,925.,850.,700.,600.,500.,400.,300.,200.,100.,50.,10.]

# FNL数据变量名
fnl_varname:
  u: 'UGRD_P0_L100_GLL0' # [m/s]
  v: 'VGRD_P0_L100_GLL0' # [m/s]
  t: 'TMP_P0_L100_GLL0' # [K]
  h: 'HGT_P0_L100_GLL0' # [gpm]
  rh: 'RH_P0_L100_GLL0' # [%]
  p_pa: 'lv_ISBL0' # [Pa]

# GRAPES数据变量名
grapes_varname:
  u: 'u'
  v: 'v'
  t: 't'
  h: 'h'
  w_m2s: 'w'
  q_kg2kg: 'q2'
  lat: 'latitude'
  lon: 'longitude'
  lev: 'levels'
  time: 'times'
  rainc: 'rainc'
  rainnc: 'rainnc'
  t2m: 't2m'
  hf: 'hfxa'
  qf: 'qfxa'

variable_name:
  t:  'Temperature [K]'
  u:  'U Wind [m/s]'
  v:  'V wind [m/s]'
  h:  'Geopotential Height [gpm]'
  w:  'Vertical Velocity [cm/s]'
  q: 'Specific Humidity [g/kg]'
  24hrain: '+24hr Precipitation [mm]'
  t2m: '2m Temperature [K]'
  shf: '24hr Mean Surface Sensible Heat Flux [$W \cdot m^{-2} \cdot s^{-1}$]'
  phf: '24hr Mean Surface Latent Heat Flux [$W \cdot m^{-2} \cdot s^{-1}$]'

# 可画图变量
plotable_vars: ['u','v','t','h','w','q','24hrain','t2m', 'shf', 'phf']

# 画图归一化参数
symlognorm_params:
  w:
    linthresh: 1
    linscale: 1.2
    vmin: -32
    vmax: 32
  shf:
    linthresh: 80
    linscale: 1.4
    vmin: -200
    vmax: 800

lognorm_params:
  24hrain:

# 填色色标间隔
clevel_step:
  u: 2
  v: 2
  t: 1
  h: 30
  q: 0.1
  t2m: 1
  shf: 10
  phf: 10

clevel_step_PMF:
  u: 1
  v: 1
  t: 0.3
  h: 10
  q: 0.1

# 自定义clevels
clevel_custom:
  24hrain: [0.1, 1, 2, 4, 6, 8, 10, 12, 16, 20, 32, 64]
  w: [-32, -16, -8, -4, -2, -1, -0.5, -0.2, 0, 0.2, 0.5, 1, 2, 4, 6, 8, 16, 32]
  shf: [-200, -100, -50, -25, 0, 25, 50, 100, 200, 400, 800]

# 一些特殊变量
# avoid ploting initial
moist_vars : ['q', 'w', 't2m']

# avoid ploting FNL
noFNL_vars: ['24hrain', 'w', 't2m', 'shf', 'phf']

# align with 00z vars
align_vars: ['24hrain']

# 24hmean var
daymean_vars: ['shf', 'phf']

# 图片质量
plot_dpi: 300
# 是否制作拼图
make_comp: True
# 是否制作动图 
make_gif: False

# 原始图片路径
origin_dir: 'origin'
# 拼图路径
comp_dir: 'comp'
# 动图路径
gif_dir: 'gif'
# 案例图路径
case_dir: 'case'
